# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.core.validators
import django.utils.timezone
import finances.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), finances.validators.validate_positive_amount], verbose_name='Montant total (Ar)')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('categorie', models.CharField(choices=[('fonctionnement', '🏢 Fonctionnement'), ('investissement', '📈 Investissement'), ('personnel', '👥 Personnel'), ('formation', '🎓 Formation'), ('mission', '✈️ Mission'), ('autre', '📦 Autre')], default='fonctionnement', max_length=20, verbose_name='Catégorie')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire (Ar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('en_attente', '🟡 En attente'), ('verifiee', '🔵 Vérifiée'), ('validee', '🟢 Validée'), ('payee', '✅ Payée'), ('rejetee', '🔴 Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='depenses/pieces/%Y/%m/', validators=[finances.validators.validate_file_size], verbose_name='Pièce justificative')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_validation_comptable', models.DateTimeField(blank=True, null=True, verbose_name='Date validation comptable')),
                ('date_validation_dg', models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
            ],
            options={
                'verbose_name': '💰 Dépense',
                'verbose_name_plural': '💰 Dépenses',
                'ordering': ['-created_at'],
                'permissions': [('can_verify_depense', 'Peut vérifier une dépense'), ('can_validate_depense', 'Peut valider une dépense'), ('can_pay_depense', 'Peut payer une dépense')],
            },
        ),
        migrations.CreateModel(
            name='EntreeArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), finances.validators.validate_positive_amount, finances.validators.validate_entree_montant], verbose_name='Montant (Ar)')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('mode_paiement', models.CharField(choices=[('especes', '💵 Espèces'), ('virement', '🏦 Virement'), ('cheque', '📄 Chèque'), ('carte', '💳 Carte bancaire'), ('mobile', '📱 Paiement mobile')], max_length=20, verbose_name='Mode de paiement')),
                ('date_entree', models.DateField(default=django.utils.timezone.now, validators=[finances.validators.validate_future_date], verbose_name="Date d'entrée")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('en_attente', '🟡 En attente'), ('confirmee', '🟢 Confirmée'), ('annulee', '🔴 Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='entrees/pieces/%Y/%m/', validators=[finances.validators.validate_file_size], verbose_name='Pièce justificative')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'db_table': 'finances_entree_argent',
            },
        ),
    ]
