# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='depense',
            name='valide_par_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees_comptable', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (comptable)'),
        ),
        migrations.AddField(
            model_name='depense',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees_dg', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (DG)'),
        ),
        migrations.AddField(
            model_name='entreeargent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['numero'], name='finances_en_numero_411ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['date_entree'], name='finances_en_date_en_609e50_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['statut'], name='finances_en_statut_a567aa_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['created_by'], name='finances_en_created_67c62d_idx'),
        ),
    ]
