# Generated by Django 5.1.15 on 2026-01-31 17:11

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import finances.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finances', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('old_statut', models.CharField(max_length=30)),
                ('new_statut', models.CharField(max_length=30)),
                ('action', models.CharField(help_text='Ex: confirm, cancel, verify, validate, pay, reject', max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finances_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-created_at'], 'permissions': [('can_verify_depense', 'Peut vérifier une dépense'), ('can_validate_depense', 'Peut valider une dépense'), ('can_pay_depense', 'Peut payer une dépense'), ('can_reject_depense', 'Peut rejeter une dépense')], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='entreeargent',
            options={'ordering': ['-date_entree', '-created_at'], 'permissions': [('can_confirm_entree', "Peut confirmer une entrée d'argent"), ('can_cancel_entree', "Peut annuler une entrée d'argent"), ('can_view_all_entrees', 'Peut voir toutes les entrées'), ('can_export_entrees', 'Peut exporter les entrées')], 'verbose_name': "Entrée d'argent", 'verbose_name_plural': "Entrées d'argent"},
        ),
        migrations.RemoveIndex(
            model_name='entreeargent',
            name='finances_en_numero_411ebd_idx',
        ),
        migrations.RemoveIndex(
            model_name='entreeargent',
            name='finances_en_date_en_609e50_idx',
        ),
        migrations.RemoveIndex(
            model_name='entreeargent',
            name='finances_en_statut_a567aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='entreeargent',
            name='finances_en_created_67c62d_idx',
        ),
        migrations.AddField(
            model_name='depense',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AddField(
            model_name='depense',
            name='historique',
            field=models.TextField(blank=True, help_text='Journal des modifications', verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='depense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='depense',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_verifiees', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='entreeargent',
            name='historique',
            field=models.TextField(blank=True, help_text='Journal des modifications', verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='entreeargent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('fonctionnement', 'Fonctionnement'), ('investissement', 'Investissement'), ('personnel', 'Personnel'), ('formation', 'Formation'), ('mission', 'Mission'), ('autre', 'Autre')], default='fonctionnement', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Informations complémentaires', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant calculé automatiquement (quantité × prix unitaire)', max_digits=12, validators=[finances.validators.validate_positive_amount], verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='motif',
            field=models.CharField(help_text='Description de la dépense', max_length=200, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='numero',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='piece_justificative',
            field=models.FileField(blank=True, help_text='Justificatif de la dépense (max 5MB)', null=True, upload_to='depenses/pieces_justificatives/%Y/%m/', validators=[finances.validators.validate_file_size, finances.validators.validate_file_extension], verbose_name='Pièce justificative'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='quantite',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'unités", verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('verifiee', 'Vérifiée'), ('validee', 'Validée'), ('payee', 'Payée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Informations complémentaires', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='date_entree',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant en Ariary (entre 1,000.00 et 1,000,000,000.00 Ar)', max_digits=12, validators=[finances.validators.validate_positive_amount, finances.validators.validate_entree_montant], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='motif',
            field=models.CharField(help_text="Description de l'entrée d'argent", max_length=200, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='numero',
            field=models.CharField(db_index=True, editable=False, help_text='Numéro unique généré automatiquement', max_length=20, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='piece_justificative',
            field=models.FileField(blank=True, help_text='Fichier PDF, JPG, PNG ou DOC (max 5MB)', null=True, upload_to='entrees/pieces_justificatives/%Y/%m/', validators=[finances.validators.validate_file_size, finances.validators.validate_file_extension], verbose_name='Pièce justificative'),
        ),
        migrations.AlterField(
            model_name='entreeargent',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['statut', 'categorie'], name='finances_de_statut_8e1505_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['created_by', 'statut'], name='finances_de_created_44f3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['montant'], name='finances_de_montant_5db143_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['created_at'], name='finances_de_created_731e62_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['verifie_par'], name='finances_de_verifie_dd0b80_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['date_entree', 'statut'], name='finances_en_date_en_aa3113_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['created_by', 'statut'], name='finances_en_created_41ff26_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['montant'], name='finances_en_montant_0e5589_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeargent',
            index=models.Index(fields=['mode_paiement'], name='finances_en_mode_pa_f85577_idx'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='montant_depense_positif'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gt', 0)), name='prix_unitaire_positif'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['en_attente', 'verifiee', 'validee', 'payee', 'rejetee'])), name='statut_depense_valide'),
        ),
        migrations.AddConstraint(
            model_name='entreeargent',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('1000.00'))), name='montant_min_entree'),
        ),
        migrations.AddConstraint(
            model_name='entreeargent',
            constraint=models.CheckConstraint(condition=models.Q(('date_entree__lte', datetime.date(2026, 1, 31))), name='date_entree_non_future'),
        ),
        migrations.AddConstraint(
            model_name='entreeargent',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['en_attente', 'confirmee', 'annulee'])), name='statut_entree_valide'),
        ),
        migrations.AlterModelTable(
            name='depense',
            table='finances_depense',
        ),
        migrations.AddField(
            model_name='financehistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financehistory',
            index=models.Index(fields=['content_type', 'object_id'], name='finances_hi_content_6b18fc_idx'),
        ),
        migrations.AddIndex(
            model_name='financehistory',
            index=models.Index(fields=['user'], name='finances_hi_user_id_dae32e_idx'),
        ),
        migrations.AddIndex(
            model_name='financehistory',
            index=models.Index(fields=['created_at'], name='finances_hi_created_530056_idx'),
        ),
    ]
