# Generated by Django 5.1.15 on 2026-02-07 06:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_financehistory_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entreeargent',
            name='date_entree_non_future',
        ),
        migrations.AddConstraint(
            model_name='entreeargent',
            constraint=models.CheckConstraint(condition=models.Q(('date_entree__lte', datetime.date(2026, 2, 7))), name='date_entree_non_future'),
        ),
        migrations.DeleteModel(
            name='FinanceHistory',
        ),
    ]
