# Generated by Django 5.1.15 on 2026-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_financehistory_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la séquence')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Dernière valeur')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compteur de séquence',
                'db_table': 'ipmf_sequences',
            },
        ),
    ]
