# Generated by Django 5.1.15 on 2026-02-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_entreeargent_date_entree_non_future_and_more'),
        ('tasks', '0008_demandereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-created_at'], 'permissions': [('can_verify_depense', 'Peut vérifier une dépense'), ('can_validate_depense', 'Peut valider une dépense'), ('can_pay_depense', 'Peut payer une dépense'), ('can_reject_depense', 'Peut rejeter une dépense'), ('can_approve_mission_expenses', 'Peut auto-valider via mission')], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),

        migrations.AddField(
            model_name='depense',
            name='approved_by_system',
            field=models.BooleanField(default=False, help_text='Auto-approuvé via règles métier', verbose_name='Auto-approbation système'),
        ),
        migrations.AddField(
            model_name='depense',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='tasks.tache', verbose_name='Mission liée'),
        ),
    ]
