# Generated by Django 5.1.15 on 2026-03-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_depense_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entreeargent',
            name='date_entree_non_future',
        ),
    ]
