# Generated by Django 5.1.15 on 2026-04-12 06:29

import datetime
import django.core.validators
import django.db.models.deletion
import students.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la formation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_mois', models.PositiveIntegerField(default=12, verbose_name='Durée (mois)')),
                ('frais_defaut', models.DecimalField(decimal_places=2, default=0, help_text='Montant par défaut des frais de formation', max_digits=12, verbose_name='Frais par défaut (Ar)')),
                ('nombre_tranches_defaut', models.PositiveIntegerField(default=3, verbose_name='Nombre de tranches par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscription', models.CharField(editable=False, max_length=20, unique=True, verbose_name="Numéro d'inscription")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('cin', models.CharField(blank=True, max_length=30, verbose_name='N° CIN')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.photo_etudiant_upload, verbose_name='Photo')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+261321234567'. 9-15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2025-2026', max_length=9, verbose_name='Année scolaire')),
                ('date_inscription', models.DateField(default=datetime.date.today, verbose_name="Date d'inscription")),
                ('montant_total_frais', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total des frais (Ar)')),
                ('nombre_tranches', models.PositiveIntegerField(default=3, verbose_name='Nombre de tranches')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('abandonne', 'Abandonné')], default='actif', max_length=15, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_inscrits', to=settings.AUTH_USER_MODEL, verbose_name='Inscrit par')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='students.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.PositiveIntegerField(verbose_name='N° de tranche')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant prévu (Ar)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé (Ar)')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('partiel', 'Partiel')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence reçu/bordereau')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='students.etudiant', verbose_name='Étudiant')),
                ('recu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_recus', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Paiement de frais',
                'verbose_name_plural': 'Paiements de frais',
                'ordering': ['etudiant', 'numero_tranche'],
                'unique_together': {('etudiant', 'numero_tranche')},
            },
        ),
    ]
