# Generated by Django 5.1.15 on 2026-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.CharField(blank=True, help_text='Ex: 5, Promo 5', max_length=50, verbose_name='Promotion'),
        ),
    ]
