# Generated by Django 5.2.7 on 2025-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('depense_attente', '💰 Dépense en attente'), ('budget_seuil', '📊 Budget seuil atteint'), ('tache_retard', '⏰ Tâche en retard'), ('tresorerie_bas', '💸 Trésorerie basse'), ('validation_requise', '✅ Validation requise'), ('systeme', '🔧 Alerte système'), ('information', 'ℹ️ Information')], max_length=50, verbose_name="Type d'alerte")),
                ('niveau', models.CharField(choices=[('faible', '🟢 Faible'), ('moyen', '🟡 Moyen'), ('eleve', '🟠 Élevé'), ('critique', '🔴 Critique')], default='moyen', max_length=20, verbose_name='Niveau')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('lien_objet', models.CharField(blank=True, max_length=500, verbose_name="Lien vers l'objet")),
                ('donnees_contexte', models.JSONField(blank=True, default=dict, verbose_name='Données de contexte')),
            ],
            options={
                'verbose_name': '🔔 Alerte',
                'verbose_name_plural': '🔔 Alertes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict, verbose_name='Configuration du layout')),
                ('favorite_widgets', models.JSONField(default=list, verbose_name='Widgets favoris')),
                ('default_view', models.CharField(choices=[('overview', "Vue d'ensemble"), ('financial', 'Vue financière'), ('tasks', 'Vue tâches'), ('custom', 'Vue personnalisée')], default='overview', max_length=50, verbose_name='Vue par défaut')),
                ('refresh_interval', models.IntegerField(choices=[(60, '1 minute'), (300, '5 minutes'), (600, '10 minutes'), (1800, '30 minutes')], default=300, verbose_name='Intervalle de rafraîchissement (secondes)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': '⚙️ Préférence Dashboard',
                'verbose_name_plural': '⚙️ Préférences Dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict)),
                ('est_public', models.BooleanField(default=False)),
                ('est_defaut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '👁️ Vue Dashboard',
                'verbose_name_plural': '👁️ Vues Dashboard',
                'ordering': ['-est_defaut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('financial_summary', '📊 Résumé financier'), ('task_overview', "📋 Vue d'ensemble des tâches"), ('recent_activities', '🔄 Activités récentes'), ('alerts_panel', "🔔 Panel d'alertes"), ('charts', '📈 Graphiques'), ('quick_actions', '⚡ Actions rapides')], max_length=50)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=3)),
                ('config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🧩 Configuration Widget',
                'verbose_name_plural': '🧩 Configurations Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
