# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='dashboardpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['destinataire', 'lue'], name='dashboard_a_destina_258c32_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['date_creation'], name='dashboard_a_date_cr_13baa5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type_alerte'], name='dashboard_a_type_al_755015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetconfig',
            unique_together={('user', 'widget_type')},
        ),
    ]
