# Generated by Django 5.1.15 on 2026-02-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Alerte', 'verbose_name_plural': 'Alertes'},
        ),
        migrations.AlterModelOptions(
            name='dashboardpreferences',
            options={'verbose_name': 'Preference Dashboard', 'verbose_name_plural': 'Preferences Dashboard'},
        ),
        migrations.AlterModelOptions(
            name='dashboardview',
            options={'ordering': ['-est_defaut', 'nom'], 'verbose_name': 'Vue Dashboard', 'verbose_name_plural': 'Vues Dashboard'},
        ),
        migrations.AlterModelOptions(
            name='widgetconfig',
            options={'ordering': ['position_y', 'position_x'], 'verbose_name': 'Configuration Widget', 'verbose_name_plural': 'Configurations Widgets'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='niveau',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Eleve'), ('critique', 'Critique')], default='moyen', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type_alerte',
            field=models.CharField(choices=[('depense_attente', 'Depense en attente'), ('budget_seuil', 'Budget seuil atteint'), ('tache_retard', 'Tache en retard'), ('tresorerie_bas', 'Tresorerie basse'), ('validation_requise', 'Validation requise'), ('systeme', 'Alerte systeme'), ('information', 'Information')], max_length=50, verbose_name="Type d'alerte"),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='widget_type',
            field=models.CharField(choices=[('financial_summary', 'Resume financier'), ('task_overview', "Vue d'ensemble des taches"), ('recent_activities', 'Activites recentes'), ('alerts_panel', "Panel d'alertes"), ('charts', 'Graphiques'), ('quick_actions', 'Actions rapides')], max_length=50),
        ),
    ]
