# Generated by Django 5.1.15 on 2026-02-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_globalmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalMessage',
        ),
    ]
