# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '👑 Administrateur Système'), ('dg', '💼 Directeur Général'), ('comptable', '💰 Comptable'), ('caisse', '💵 Responsable Caisse'), ('agent', '👤 Agent'), ('superviseur_it', '🔧 Superviseur IT')], default='agent', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+261321234567'. 9-15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '👤 Utilisateur',
                'verbose_name_plural': '👥 Utilisateurs',
                'ordering': ['-date_created'],
                'permissions': [('can_manage_users', 'Peut gérer les utilisateurs'), ('can_view_reports', 'Peut voir les rapports'), ('can_export_data', 'Peut exporter les données')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='Signature')),
                ('notifications_active', models.BooleanField(default=True, verbose_name='Notifications activées')),
                ('theme_preference', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], default='fr', max_length=10, verbose_name='Langue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📋 Profil Utilisateur',
                'verbose_name_plural': '📋 Profils Utilisateurs',
            },
        ),
    ]
