# Generated by Django 5.1.15 on 2026-02-07 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_created'], 'permissions': [('can_manage_users', 'Peut gérer les utilisateurs'), ('can_view_reports', 'Peut voir les rapports'), ('can_export_data', 'Peut exporter les données')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Derniere modification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur Systeme'), ('dg', 'Directeur General'), ('comptable', 'Comptable'), ('caisse', 'Responsable Caisse'), ('agent', 'Agent'), ('superviseur_it', 'Superviseur IT')], default='agent', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+261321234567'. 9-15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telephone'),
        ),
    ]
