# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', '🆕 Création'), ('read', '👁️ Consultation'), ('update', '✏️ Modification'), ('delete', '🗑️ Suppression'), ('login', '🔐 Connexion'), ('logout', '🚪 Déconnexion'), ('export', '📤 Export'), ('import', '📥 Import'), ('validation', '✅ Validation'), ('rejet', '❌ Rejet'), ('system', '⚙️ Système')], max_length=20, verbose_name="Type d'action")),
                ('module', models.CharField(choices=[('users', '👥 Utilisateurs'), ('finances', '💰 Finances'), ('tasks', '📋 Tâches'), ('dashboard', '📊 Dashboard'), ('audit', '🔍 Audit'), ('system', '⚙️ Système'), ('auth', '🔐 Authentification')], max_length=20, verbose_name='Module')),
                ('niveau', models.CharField(choices=[('info', 'ℹ️ Information'), ('warning', '⚠️ Avertissement'), ('error', '🔴 Erreur'), ('critical', '💥 Critique')], default='info', max_length=20, verbose_name='Niveau')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('objet_type', models.CharField(blank=True, max_length=100, verbose_name="Type d'objet")),
                ('objet_id', models.CharField(blank=True, max_length=100, verbose_name="ID de l'objet")),
                ('objet_repr', models.CharField(blank=True, max_length=255, verbose_name="Représentation de l'objet")),
                ('message', models.TextField(verbose_name='Message')),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('differences', models.JSONField(blank=True, null=True, verbose_name='Différences')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Clé de session')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Code statut HTTP')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Durée (ms)')),
            ],
            options={
                'verbose_name': "📝 Entrée d'audit",
                'verbose_name_plural': "📝 Entrées d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('format', models.CharField(choices=[('excel', '📊 Excel'), ('pdf', '📄 PDF'), ('csv', '📋 CSV'), ('json', '🔤 JSON')], max_length=10, verbose_name='Format')),
                ('module', models.CharField(choices=[('users', '👥 Utilisateurs'), ('finances', '💰 Finances'), ('tasks', '📋 Tâches'), ('dashboard', '📊 Dashboard'), ('audit', '🔍 Audit'), ('system', '⚙️ Système'), ('auth', '🔐 Authentification')], max_length=20, verbose_name='Module')),
                ('fichier', models.FileField(upload_to='exports/%Y/%m/', verbose_name='Fichier exporté')),
                ('parametres', models.JSONField(default=dict, verbose_name="Paramètres d'export")),
                ('nombre_lignes', models.IntegerField(blank=True, null=True, verbose_name='Nombre de lignes')),
                ('taille_fichier', models.BigIntegerField(verbose_name='Taille du fichier (octets)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "📤 Historique d'export",
                'verbose_name_plural': "📤 Historiques d'export",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('reussi', models.BooleanField(default=True, verbose_name='Connexion réussie')),
                ('raison_echec', models.CharField(blank=True, max_length=100, verbose_name="Raison de l'échec")),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Clé de session')),
            ],
            options={
                'verbose_name': '🔐 Historique de connexion',
                'verbose_name_plural': '🔐 Historiques de connexion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('type_check', models.CharField(choices=[('performance', '⚡ Performance'), ('security', '🛡️ Sécurité'), ('database', '🗄️ Base de données'), ('storage', '💾 Stockage'), ('network', '🌐 Réseau'), ('backup', '📦 Sauvegarde'), ('cleanup', '🧹 Nettoyage')], max_length=20, verbose_name='Type de vérification')),
                ('niveau', models.CharField(choices=[('info', 'ℹ️ Information'), ('warning', '⚠️ Avertissement'), ('error', '🔴 Erreur'), ('critical', '💥 Critique')], max_length=20, verbose_name='Niveau')),
                ('composant', models.CharField(max_length=100, verbose_name='Composant')),
                ('message', models.TextField(verbose_name='Message')),
                ('metriques', models.JSONField(default=dict, verbose_name='Métriques')),
                ('duree_execution', models.FloatField(blank=True, null=True, verbose_name="Durée d'exécution (ms)")),
            ],
            options={
                'verbose_name': '❤️ Journal de santé système',
                'verbose_name_plural': '❤️ Journaux de santé système',
                'ordering': ['-timestamp'],
            },
        ),
    ]
