# Generated by Django 5.1.15 on 2026-02-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', '🆕 Création'), ('read', '👁️ Consultation'), ('update', '✏️ Modification'), ('delete', '🗑️ Suppression'), ('login', '🔐 Connexion'), ('logout', '🚪 Déconnexion'), ('export', '📤 Export'), ('import', '📥 Import'), ('validation', '✅ Validation'), ('payment', '💳 Paiement'), ('rejet', '❌ Rejet'), ('system', '⚙️ Système')], max_length=20, verbose_name="Type d'action"),
        ),
    ]
