# Generated by Django 5.1.15 on 2026-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Entree d'audit", 'verbose_name_plural': "Entrees d'audit"},
        ),
        migrations.AlterModelOptions(
            name='exporthistory',
            options={'ordering': ['-timestamp'], 'verbose_name': "Historique d'export", 'verbose_name_plural': "Historiques d'export"},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Historique de connexion', 'verbose_name_plural': 'Historiques de connexion'},
        ),
        migrations.AlterModelOptions(
            name='systemhealthlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Journal de sante systeme', 'verbose_name_plural': 'Journaux de sante systeme'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Creation'), ('read', 'Consultation'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Deconnexion'), ('export', 'Export'), ('import', 'Import'), ('validation', 'Validation'), ('payment', 'Paiement'), ('rejet', 'Rejet'), ('system', 'Systeme')], max_length=20, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('users', 'Utilisateurs'), ('finances', 'Finances'), ('tasks', 'Taches'), ('dashboard', 'Dashboard'), ('audit', 'Audit'), ('system', 'Systeme'), ('auth', 'Authentification')], max_length=20, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='niveau',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='format',
            field=models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='module',
            field=models.CharField(choices=[('users', 'Utilisateurs'), ('finances', 'Finances'), ('tasks', 'Taches'), ('dashboard', 'Dashboard'), ('audit', 'Audit'), ('system', 'Systeme'), ('auth', 'Authentification')], max_length=20, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='systemhealthlog',
            name='niveau',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='systemhealthlog',
            name='type_check',
            field=models.CharField(choices=[('performance', 'Performance'), ('security', 'Securite'), ('database', 'Base de donnees'), ('storage', 'Stockage'), ('network', 'Reseau'), ('backup', 'Sauvegarde'), ('cleanup', 'Nettoyage')], max_length=20, verbose_name='Type de vérification'),
        ),
    ]
