# Generated by Django 5.1.15 on 2026-02-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_options_alter_exporthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Méthode HTTP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objet_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Représentation de l'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objet_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé de session'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
