# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '💬 Commentaire de tâche',
                'verbose_name_plural': '💬 Commentaires de tâche',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('priorite', models.CharField(choices=[('basse', '🟢 Basse'), ('moyenne', '🟡 Moyenne'), ('haute', '🔴 Haute'), ('urgente', '⚠️ Urgente')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('creee', '🟡 Créée'), ('en_cours', '🔵 En cours'), ('terminee', '🟢 Terminée'), ('validee', '✅ Validée'), ('annulee', '🔴 Annulée')], default='creee', max_length=20, verbose_name='Statut')),
                ('budget_alloue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget alloué (Ar)')),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat')),
                ('piece_jointe_resultat', models.FileField(blank=True, null=True, upload_to='taches/resultats/%Y/%m/', verbose_name='Pièce jointe (résultat)')),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': '📋 Tâche',
                'verbose_name_plural': '📋 Tâches',
                'ordering': ['-date_creation'],
                'permissions': [('can_assign_tasks', 'Peut assigner des tâches'), ('can_validate_tasks', 'Peut valider des tâches')],
            },
        ),
    ]
