# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairetache',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tache',
            name='agent_assigné',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné'),
        ),
        migrations.AddField(
            model_name='tache',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='tache',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taches_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='commentairetache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='tasks.tache'),
        ),
    ]
