# Generated by Django 5.2.7 on 2026-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairetache',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='taches/commentaires/%Y/%m/', verbose_name='Pièce jointe'),
        ),
    ]
