# Generated by Django 5.1.15 on 2026-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_commentairetache_piece_jointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_echeance',
            field=models.DateTimeField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('creee', 'Créée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='creee', max_length=20, verbose_name='Statut'),
        ),
    ]
