# Generated by Django 5.1.15 on 2026-01-31 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tache_date_debut_alter_tache_date_echeance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='agent_assigné',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné'),
        ),
    ]
