# Generated by Django 5.1.15 on 2026-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tache_agent_assigne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='agent_assigné',
            new_name='agent_assigne',
        ),
    ]
