# Generated by Django 5.1.15 on 2026-02-07 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_agent_assigné_tache_agent_assigne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='agent_assigne',
        ),
        migrations.AddField(
            model_name='tache',
            name='agents_assignes',
            field=models.ManyToManyField(blank=True, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Agents assignés'),
        ),
    ]
