# Generated by Django 5.1.15 on 2026-02-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tache_agent_assigne_tache_agents_assignes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demandee', models.DateTimeField(verbose_name="Nouvelle date d'échéance souhaitée")),
                ('motif', models.TextField(verbose_name='Motif du report')),
                ('pj_justificatif', models.FileField(blank=True, null=True, upload_to='taches/reports/', verbose_name='Pièce jointe justificative')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('commentaire_reponse', models.TextField(blank=True, verbose_name='Commentaire de réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_report_emises', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('repondu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_report_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_report', to='tasks.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': '📅 Demande de report',
                'verbose_name_plural': '📅 Demandes de report',
                'ordering': ['-date_creation'],
            },
        ),
    ]
