# Generated by Django 5.1.15 on 2026-02-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_demandereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la sous-tâche')),
                ('est_terminee', models.BooleanField(default=False, verbose_name='Terminée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='tasks.tache', verbose_name='Mission parente')),
            ],
            options={
                'verbose_name': ' Sous-tâche',
                'verbose_name_plural': ' Sous-tâches',
                'ordering': ['date_creation'],
            },
        ),
    ]
