# Generated by Django 5.1.15 on 2026-02-25 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_soustache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='agent_principal',
            field=models.ForeignKey(blank=True, help_text='Responsable du démarrage et de la clôture. Si non défini, le premier agent assigné est utilisé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_comme_principal', to=settings.AUTH_USER_MODEL, verbose_name='Agent principal (responsable)'),
        ),
    ]
