# Generated by Django 5.1.15 on 2026-04-11 22:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_agent_principal_to_tache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Article / Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, default='', max_length=50, verbose_name='Unité (ex: L, kg, pièce)')),
                ('prix_estime', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire estimé (Ar)')),
                ('prix_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire réel (Ar)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='tasks.tache', verbose_name='Mission')),
            ],
            options={
                'verbose_name': '📋 Ligne de devis',
                'verbose_name_plural': '📋 Lignes de devis',
                'ordering': ['date_creation'],
            },
        ),
    ]
